name: Docker Image CI

on:
  push:
    branches: [ "decent-e" ]
  pull_request:
    branches: [ "decent-e" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      -
        name: Build
        run: |
          docker build --platform "linux/amd64,linux/arm64" --push . --file Dockerfile --tag ghcr.io/decent-e/cpu:$(date +%s) # will run buildx
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
